### ISSUE TITLE
[UI/UX] view by project

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/oso#100]
### Describe the feature you'd like to request

Given a project
`/projects/id`

Let the user see all the associated artifacts and visualize event data

### Describe the solution you'd like

Project page

### Describe alternatives you've considered

N/A

**Comment by ccerv1** [comment]
Also see context on #101

**Comment by ccerv1** [comment]
@ryscheng closing this out for now. Here's the UI I'm envisioning.

As a user viewing a project, I can:
- select a standard or custom date range to view metrics
- quickly learn (and click for more info):
   - whether a project is verified
   - when the last indexing job ran (and can request an update when I click)
   - what collections it's a part of
   - what artifacts it has linked
- view different metrics
   - activity
       - work inputs (eg, github contributions, package releases, contracts deployed)
       - each one has a powerful dataviz plus widgets for KPIs
       - each element shows a headline indicator and a growth rate over the period
   - impact
       - outcomes (eg, active project + downstream developers, num dependencies, onchain user analytics)
       - similar pattern as above
   - finances
       - grant income
       - burn rate
       - transaction fees

![Image](https://github.com/hypercerts-org/oso/assets/42869436/ac7cdffb-7f94-4dc4-8c54-0ce8b41b3ff1)

**Comment by ryscheng** [comment]
@ccerv1 FYI, this was originally meant to capture actually building out the entire UX. I'm okay with down-scoping this to just the UI design, and I'll open a separate issue for the actual page functionality.

Continuing here https://github.com/hypercerts-org/oso/issues/138
