### ISSUE TITLE
A user can see the `financing` of a project

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/oso#149]
- [ ] Grants received (in whatever token the grant was given in)
- [ ] Current net worth (across all addresses in USD)

![Image](https://github.com/hypercerts-org/oso/assets/42869436/196a8e67-485b-4e1d-82ab-71d164b78297)

![Image](https://github.com/hypercerts-org/oso/assets/42869436/4464fd04-ad58-42f1-9b22-e8d82f8ae9ba)

**Comment by ryscheng** [comment]
Closing this in favor of 
https://github.com/hypercerts-org/oso/issues/187
https://github.com/hypercerts-org/oso/issues/138
