### ISSUE TITLE
Index onchain event metrics

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/oso#37]
# Impact
- [x] Transactions
- [x] Internal transactions [nice to have]
- [x] Gas fees generated
- [x] Number of unique addresses interacting with the contract
- [x] Number of monthly active users
- [x] Number of returning users over a given period

# Activity
- [ ] Contracts deployed

# Financing
- [ ] Grants received
- [ ] Funds dispersed
- [ ] Token transfers (send/receive)
- [ ] Expenses

**Comment by ccerv1** [comment]
@ryscheng the stats included in [this dune query](https://dune.com/queries/502559/950799) are very relevant



![Image](https://github.com/hypercerts-org/oso/assets/42869436/aa714902-7b5c-49c8-92c8-694b6e5d57d6)

**Comment by ccerv1** [comment]
@ryscheng to create a new issue for anything that DOESN'T get hit by issue #2

**Comment by ryscheng** [comment]
Gonna close this in favor of 

https://github.com/hypercerts-org/oso/issues/186
https://github.com/hypercerts-org/oso/issues/185
