### ISSUE TITLE
Retrieve GitHub event data for a repository

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/oso#6]
### Describe the feature you'd like to request

We want the following:

- [x] Issues created
- [x] Issues closed
- [x] PRs created
- [x] PRs merged
- [x] Commits
- [x] Code reviews
- [x] Forks
- [x] Stargazers

Depends on https://github.com/hypercerts-org/os-observer/issues/56

### Describe the solution you'd like

Build on https://github.com/hypercerts-org/os-observer/issues/56 to get more event data for a repository

### Describe alternatives you've considered

N/A

**Comment by ravenac95** [comment]
Got 'em 🚀
