### ISSUE TITLE
[os] an project can get a dashboard of relevant impact / activity metrics

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/oso#7]
### What is it?

Ideally users can get a snapshot of how they perform against various metrics, creating incentives for them to want to improve and have a complete profile (and rank high on lists). It may be necessary to have some credentialing on which metrics are available to all versus organization owners only.

**Comment by ryscheng** [comment]
Im gonna close this as a duplicate of https://github.com/hypercerts-org/oso/issues/138
