### ISSUE TITLE
[hackathon] create EAS schema and attest to 10+ Optimism projects

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/oso#78]
### What is it?

take the ~500 or so labeled contracts and map them to github repos

**Comment by ryscheng** [comment]
https://github.com/duneanalytics/spellbook/blob/main/models/contracts/optimism/contracts_optimism_contract_creator_address_list.sql
https://github.com/hypercerts-org/oso/blob/main/indexer/helpers/contract_mapper/data/op_contract_mapping.yaml

**Comment by ryscheng** [comment]
Notes from today:
- Let's create a GitHub-curated list of contracts => GitHub repo
- We can add a simple utility script that will iterate over the (contract address, GitHub repo) entries and create EAS attestations for each if it does not exist
- We will probably manually create the initial list ourselves

**Comment by ccerv1** [comment]
See also issue #87 
Here is some inspiration for what a utility script that creates attestations could look like: https://github.com/ethereum-optimism/ecosystem-contributions/issues/67

**Comment by ccerv1** [comment]
We may want to consider if there are checks the script can run, eg, determining what kind of contract it is, whether it came from a factory or not, whether it's been verified, etc.

**Comment by ccerv1** [comment]
Note: see also [this discussion](https://github.com/hypercerts-org/oso/issues/81#issuecomment-1657214634)

**Comment by ccerv1** [comment]
https://optimism-goerli-bedrock.easscan.org/attestation/view/0x79581be34dbce820c7f7f3da5694b6e3e7d32d94ff592ffb9cb294f4c352c013
