### ISSUE TITLE
Apply to ETH global impact hackathon

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/oso#81]
### What is it?

Application deadline: Aug 2, 11:59PM

https://ethglobal.com/events/superhack/prizes

OP Mainnet Track
💫 Best App for RetroPGF, Public Goods, or Measuring Impact - $6K

Optimism’s [**RetroPGF](https://app.optimism.io/retropgf)** is changing the way impactful software is rewarded. The Optimism Collective funds projects that promote the growth of the Optimism ecosystem. You build projects with impact, you get paid. To achieve this, we need to be able to measure impact across the ecosystem.

For this bounty, create an app on OP Mainnet that can be used to track impact – of people, of products, of other apps, wherever you see value collecting. This can include identity tools, influence measurements, and clever uses of attestations. Bonus points: leverage Ethereum Attestation Service.

First place wins $3K; second wins $2K; third wins $1K.

**Comment by ccerv1** [comment]
I think we could apply with a basic way of tying a smart contract to a github repo via EAS:

```
// EAS schema
address attestor
address contractAddress
bytes32 githubOwner
```

alternatively

```
// EAS schema
address attestor
address contractAddress
bytes32[] githubRepos
```

bonus points if we make it so that each time the repo makes a release, another attestation can be made. 


Timing is good for building on EAS on Optimism: https://twitter.com/eas_eth/status/1685357935571177472?s=20

**Comment by ryscheng** [comment]
I'm accepted into the hackathon
@ccerv1 @ravenac95 you need to apply as well and join the team by tomorrow

**Comment by ccerv1** [comment]
OK here was my submission:

-----

## Info:

**Name**: OSS on OP Directory

**Description**: OSS projects produce many work artifacts (eg, git repos, smart contracts). But it takes inside knowledge to know where to find them.  We created a schema for mapping artifacts to OSS projects. We built an initial directory of 100+ OSS projects on OP. And we deployed it to EAS.

**Github**: https://github.com/hypercerts-org/oss-directory

### Idea: 

Our project will have three parts:

1. A schema for mapping artifacts to OSS projects. 
2. An initial directory of 100+ OSS projects that are building on Optimism.
3. A schema deployed to EAS -- and tested with 10 projects from the directory.

In our repository, you'll find schemas for defining artifacts, projects, and collections. You'll also see automated tests to verify that all data (from us or crowdsourced via a pull request) conforms to the schema. Note: all data are to be specified in YAML files.

In the ./data/ directory, you'll see an initial 100+ open source projects populated by our team. We looked at projects that had smart contracts deployed on Optimism and manually mapped them to an associated Github repo or Github orgazation. The data is not complete -- and likely never will be as new artifacts are produced everyday.

Finally, we will deploy a version of the schema on Ethereum Attestation Station. We're hoping to test the schema by submitting 10 attestations for well-known projects building on Optimism.
**Blockers**: Nope! We're just heads down buidling.

### Public URL: 

https://ethglobal.com/showcase/oss-on-op-directory-2zjfy
