### ISSUE TITLE
Import a visualization library into Plasmic as code components

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/oso#92]
### Describe the feature you'd like to request

There are many visualization libraries we could use, such as 
https://observablehq.com/plot/
https://www.tremor.so/
https://recharts.org/en-US/
https://nivo.rocks/
https://uber.github.io/react-vis/
https://echarts.apache.org/en/index.html
https://airbnb.io/visx/

### Describe the solution you'd like

Not sure which is most appropriate right now, but would be good to choose one that is sufficiently complete so that we can maintain consistent styling

### Describe alternatives you've considered

See above

**Comment by ryscheng** [comment]
@ccerv1 leaving this for you to pick a few good ones first, then I can go back and import them when we're ready

**Comment by ccerv1** [comment]
Just went through this ... 

I like Tremor a lot. Its [basic charts](https://www.tremor.so/docs/components/area-chart) and [KPI cards](https://www.tremor.so/blocks/kpi-cards) are perfect for what need straight out of the box. I would start here.

The Uber library is decent, though a bit simplistic. The [Sankey](https://uber.github.io/react-vis/examples/showcases/sankeys) is nice and clean, unlike many others out there (including Observable's). So I might just want to use that component.

The Airbnb library has a few powerful graphics that I could imagine using for the most important visualizations / landing page content. [Here](https://airbnb.io/visx/streamgraph) is an example.

**Comment by ccerv1** [comment]
@ryscheng 

I like the following from Tremor:

### [KPI Cards](https://www.tremor.so/blocks/kpi-cards) -- specifically, `Card + BadgeDelta + Text`

![Image](https://github.com/hypercerts-org/oso/assets/42869436/c376d264-a1d1-4429-a190-ee29af0d2180)

### [Area Chart](https://www.tremor.so/docs/components/area-chart)

![Image](https://github.com/hypercerts-org/oso/assets/42869436/769d8342-ea21-458f-8f92-a025c01cb6e4)

### [Bar List](https://www.tremor.so/docs/components/barlist) will be very useful for tracking repos, contracts, versions, etc

![Image](https://github.com/hypercerts-org/oso/assets/42869436/afc7bd07-0056-4b03-919f-3e2808f599f9)

### [Date Range Picker](https://www.tremor.so/docs/components/daterangepicker) is nice

**Comment by ryscheng** [comment]
https://github.com/hypercerts-org/oso/pull/158

**Comment by ryscheng** [comment]
Installing Tailwind here
https://github.com/hypercerts-org/oso/pull/174

**Comment by ryscheng** [comment]
Okay, I think this is at a good point to close, we got some working components to start with. If we want to import other components, let's file new issues for those
