### ISSUE TITLE
[UI/UX] view by artifact

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/oso#99]
### Describe the feature you'd like to request

At `/artifacts/namespace/name`, let the user browse time-series data about the artifact

### Describe the solution you'd like

Select an event type and see a chart

### Describe alternatives you've considered

N/A

**Comment by ccerv1** [comment]
Let's create reusable components for artifact widgets:

- Single metric chart

![Image](https://github.com/hypercerts-org/oso/assets/42869436/4c2d6e0b-6f82-4027-a2de-b4c0f4762178)


- Single metric tile


![Image](https://github.com/hypercerts-org/oso/assets/42869436/2869ac12-869d-4d60-8bac-59bb647443c6)

**Comment by ccerv1** [comment]
@ryscheng I've implemented both types of artifacts widgets in Plasmic. The charts use static images. I did some decent enough versions using highcharts and added them to the OSO repo [here](https://github.com/hypercerts-org/oso/pull/123)



![Image](https://github.com/hypercerts-org/oso/assets/42869436/e418f0e7-44a9-4b5a-a275-fac7f49a0cf8)

**Comment by ryscheng** [comment]
Continuing here https://github.com/hypercerts-org/oso/issues/137
